// Normally generated by Arduino IoT Cloud. This sanitized version keeps
// credentials in arduino_secrets.h, which is excluded from Git.

#pragma once

#include "arduino_secrets.h"
#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[] = SECRET_DEVICE_LOGIN_NAME;
const char SSID[]              = SECRET_SSID;
const char PASS[]              = SECRET_OPTIONAL_PASS;
const char DEVICE_KEY[]        = SECRET_DEVICE_KEY;

void onFan1Change();
void onFan2Change();
void onLight1Change();
void onLight2Change();

CloudSwitch fan1;
CloudSwitch fan2;
CloudSwitch light1;
CloudSwitch light2;

void initProperties() {
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);

  ArduinoCloud.addProperty(fan1, READWRITE, ON_CHANGE, onFan1Change);
  ArduinoCloud.addProperty(fan2, READWRITE, ON_CHANGE, onFan2Change);
  ArduinoCloud.addProperty(light1, READWRITE, ON_CHANGE, onLight1Change);
  ArduinoCloud.addProperty(light2, READWRITE, ON_CHANGE, onLight2Change);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
